### ISSUE TITLE
Youtube Service Roadmap

### ISSUE THREAD

**Issue by sogehige** [sogebot/sogeBot#5578]
- [ ] ~trigger onStreamStart and onStreamStopped events~
  - [ ] ~update events to handle twitch and youtube types e.g. we should be able to filter onStreamStart(type)~
- [ ] listen on google chat (polling through https://developers.google.com/youtube/v3/live/docs/liveChatMessages/list)
- [ ] show youtube chat in logs
- [ ] ~get new members (followers and sponsors) and trigger alerts~
- [ ] ~show youtube chat in ui tab~
- [ ] ~show youtube chat in overlay~
- [ ] ~be able to moderate chat~
- [ ] ~be able to send message as bot~
- [ ] ~set title should work independetly on twitches setTitleAndGame()~
- [ ] ~we should support login through youtube on new UI~

- [ ] **add own user gate to use their own API application**

**Comment by sogehige** [comment]
Unfortunately youtube API have very aggresive quotas.
we will need to add user gate for own youtube application to be able to do basic stuff. although we won't be able to moderate chat and another usage doesn't make sense currently, until youtube adds at least chat websockets to load it outside of youtube
